server:
  host: 10.224.199.88
  port: 12379
# tls:
#   cert: /path/to/file.pem
#   key: /path/to/file.pem

log:
  level: warn

datasource:
  type: etcd
  etcd:
    host:
      - "st.miotetcd.io.mi.srv:4001"
    prefix: /SERVICES/apisix
    timeout: 30                     # 30 seconds
    tls:
      cert: config/miot-etcd_client.pem          # path of certificate used by the etcd client
      key: config/miot-etcd_client_key.pem            # path of key used by the etcd client
      ca_file: config/miot-etcd_ca.pem
      verify: true
